### ISSUE TITLE
No module names "tops" 

### ISSUE THREAD

**Issue by petale-azerty** [hukkelas/deep_privacy2#9]
Hello dear Hukkelas, 

when i try to use deep privacy 2 for the webcam with this command line : 
_python3 anonymize.py configs/anonymizers/FB_cse.py --webcam_ 

I receive this output : 
ModuleNotFoundError: No module named 'tops' 

Can you help me with this ??

**Comment by cassepipe** [comment]
I am no expert and just like I am trying to make it work.

What I understand from your error message is that one of the dependencies is missing, namely the `tops` package.

I have no knowledge on how to manage packages in Python and it has a reputatation of being trcicky because it can mess the python packages already installed in your system... So you may want to educate yourself a bit about  that. Also I assume you are running Linux, I have no idea about windows.

My naive answer would be : Try to `pip install tops` in you terminal and see it works.
Do that with all missing packages until you don't have those errors anymore
`pip` is the python package manager.

If you get the same error with the same package name after you've installed it, that's probably because the software `pip` installed is not on your `PATH`

**Comment by hukkelas** [comment]
If you install the repository with the [setup.py](setup.py) file it should be automatically installed, following the [installation instructions](https://www.hukkelas.no/deep_privacy2/#/?id=install-with-anaconda).

If not, you can install tops with:
```
pip install git+https://github.com/hukkelas/torch_ops
```
